[platformio]
default_envs = creality_v422

[env:creality_v422]
platform = ststm32@12.1.1
board = genericSTM32F103RE
framework = arduino
board_build.ldscript = creality_v422.ld
build_flags =
  -DVECT_TAB_OFFSET=0x7000
  -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC=0
monitor_speed = 115200
